[production]
i-084e520de3a88d36a
i-0e84d34a3e5da44c8

[production:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=us-east-1
ansible_aws_ssm_bucket_name=ekerette-devops-homelab-s3-lab-136913568034
